notifications:
    on_success: never
    on_failure: never

os :
  - linux

dist:
  - xenial

# sudo:
#   - required

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start

install:
  - "pip install pybullet"
  - "pip install numpy --upgrade"
  - "pip install qibullet"
  - "python setup.py install"
  - "pip install codecov"

script:
  - cd tests
  - coverage run main_test.py

# Push the results back to codecov
after_success:
  - codecov